import { test, expect } from 'bun:test'
import {
  messageText, findAskUserQuestion, truncate, parseDecision, inWindow,
  isSynthetic, stripSystemTags, buildTurns, type RawMessage,
} from './commit-log.js'

test('messageText: string content', () => {
  expect(messageText({ type: 'user', message: { content: 'hello' } })).toBe('hello')
})

test('messageText: block content joins text blocks', () => {
  expect(messageText({
    type: 'assistant',
    message: { content: [
      { type: 'text', text: 'a' },
      { type: 'tool_use', name: 'X' },
      { type: 'text', text: 'b' },
    ] },
  })).toBe('a\nb')
})

test('findAskUserQuestion: extracts option labels', () => {
  const r = findAskUserQuestion({
    type: 'assistant',
    message: { content: [
      { type: 'tool_use', name: 'AskUserQuestion', input: {
        questions: [{ options: [{ label: 'A' }, { label: 'B' }] }],
      } },
    ] },
  })
  expect(r?.options).toEqual(['A', 'B'])
})

test('findAskUserQuestion: null when absent', () => {
  expect(findAskUserQuestion({ type: 'assistant', message: { content: 'hi' } })).toBeNull()
})

test('truncate: keeps short, marks long', () => {
  expect(truncate('abc', 10)).toBe('abc')
  expect(truncate('abcdef', 3)).toBe('abc […3 more]')
})

test('parseDecision: extracts choices', () => {
  expect(parseDecision('Your questions have been answered: "Q"="Yes"')).toBe('Yes')
  expect(parseDecision('plain text')).toBeUndefined()
})

test('isSynthetic: command/bash/hook echoes are synthetic, real text is not', () => {
  expect(isSynthetic('<command-name>/clear</command-name>')).toBe(true)
  expect(isSynthetic('<bash-input>pwd</bash-input>')).toBe(true)
  expect(isSynthetic('Caveat: The messages below were generated by the user')).toBe(true)
  expect(isSynthetic('<local-command-caveat>Caveat: The messages below')).toBe(true)
  expect(isSynthetic('use TypeScript instead')).toBe(false)
  expect(isSynthetic('Your questions have been answered: "Q"="Yes"')).toBe(false)
  expect(isSynthetic('<codex_internal_context source="goal">control</codex_internal_context>')).toBe(true)
})

test('stripSystemTags: removes reminder/hook blocks, keeps real text', () => {
  const t = 'do the thing\n<system-reminder>noise here</system-reminder>'
  expect(stripSystemTags(t)).toBe('do the thing')
  expect(stripSystemTags('<system-reminder>only noise</system-reminder>')).toBe('')
})

test('inWindow: (from, to] half-open lower bound', () => {
  const from = Date.parse('2026-05-27T00:00:00Z')
  const to = Date.parse('2026-05-27T12:00:00Z')
  expect(inWindow('2026-05-27T00:00:00Z', from, to)).toBe(false)
  expect(inWindow('2026-05-27T06:00:00Z', from, to)).toBe(true)
  expect(inWindow('2026-05-27T12:00:00Z', from, to)).toBe(true)
  expect(inWindow('2026-05-27T12:00:01Z', from, to)).toBe(false)
})

function u(line: number, ts: string, text: string): RawMessage {
  return { msg: { type: 'user', timestamp: ts, message: { content: text } }, line }
}
function a(line: number, ts: string, text: string): RawMessage {
  return { msg: { type: 'assistant', timestamp: ts, message: { content: text } }, line }
}

test('buildTurns: extracts ALL turns mechanically (ack/materiality filtering is the LLM job in SKILL Step 3a, language-agnostic)', () => {
  const raw = [
    u(1, '2026-05-27T01:00:00Z', 'use TypeScript instead'),
    u(2, '2026-05-27T01:01:00Z', 'ok'),  // standalone ack — engine keeps it; the LLM drops it in Step 3a
  ]
  const turns = buildTurns(raw, 'sess1234')
  expect(turns.length).toBe(2)
  expect(turns[0]!.userText).toBe('use TypeScript instead')
  expect(turns[0]!.line).toBe(1)
  expect(turns[1]!.userText).toBe('ok')
  expect(turns[1]!.sessionId).toBe('sess1234')
})

test('buildTurns: keeps ack that responds to an assistant proposal', () => {
  const raw = [
    a(1, '2026-05-27T01:00:00Z', 'Should I use approach A or B?'),
    u(2, '2026-05-27T01:01:00Z', 'go'),
  ]
  const turns = buildTurns(raw, 'sess1234')
  expect(turns.length).toBe(1)
  expect(turns[0]!.userText).toBe('go')
  expect(turns[0]!.precedingAssistant).toBe('Should I use approach A or B?')
})

test('buildTurns: reactive reply pairs the preceding assistant proposal', () => {
  const raw = [
    a(1, '2026-05-27T01:00:00Z', 'Option A or Option B?'),
    u(2, '2026-05-27T01:01:00Z', 'A'),
  ]
  const turns = buildTurns(raw, 'sess1234')
  expect(turns.length).toBe(1)
  expect(turns[0]!.isReactive).toBe(true)
  expect(turns[0]!.precedingAssistant).toBe('Option A or Option B?')
})

test('buildTurns: AskUserQuestion options + decision captured', () => {
  const raw: RawMessage[] = [
    { msg: { type: 'assistant', timestamp: '2026-05-27T01:00:00Z', message: { content: [
      { type: 'tool_use', name: 'AskUserQuestion', input: {
        questions: [{ options: [{ label: 'Forward' }, { label: 'Backfill' }] }],
      } },
    ] } }, line: 1 },
    u(2, '2026-05-27T01:01:00Z', 'Your questions have been answered: "mode"="Forward"'),
  ]
  const turns = buildTurns(raw, 'sess1234')
  expect(turns[0]!.options).toEqual(['Forward', 'Backfill'])
  expect(turns[0]!.decision).toBe('Forward')
})

test('buildTurns: window filter excludes out-of-range turns', () => {
  const from = Date.parse('2026-05-27T01:00:00Z')
  const raw = [
    u(1, '2026-05-27T00:30:00Z', 'too early, should be excluded'),
    u(2, '2026-05-27T02:00:00Z', 'in range, should be kept'),
  ]
  const turns = buildTurns(raw, 'sess1234', from)
  expect(turns.length).toBe(1)
  expect(turns[0]!.line).toBe(2)
})

test('buildTurns: drops synthetic messages, strips embedded reminders', () => {
  const raw = [
    u(1, '2026-05-27T01:00:00Z', '<bash-input>pwd</bash-input>'),
    u(2, '2026-05-27T01:01:00Z', '<command-name>/clear</command-name>'),
    u(3, '2026-05-27T01:02:00Z',
      'refactor the parser\n<system-reminder>hook noise</system-reminder>'),
  ]
  const turns = buildTurns(raw, 'sess1234')
  expect(turns.length).toBe(1)
  expect(turns[0]!.line).toBe(3)
  expect(turns[0]!.userText).toBe('refactor the parser')
})
